Repository Wheellog/Wheellog.Android, pull requests merged in 2020-10, with the labels that each got.

#6 fix settings
  app/src/main/java/com/cooper/wheellog/MainActivity.java
  app/src/main/java/com/cooper/wheellog/MainPreferencesFragment.java
  app/src/main/java/com/cooper/wheellog/utils/GotwayAdapter.java
  app/src/main/res/xml/preferences_gotway.xml
  app/src/main/res/xml/preferences_speed.xml
  app/src/main/res/xml/preferences_veteran.xml
  app/src/test/java/com/cooper/wheellog/utils/GotwayAdapterTest.kt
Labels: enhancement

#17 View pager
  app/src/main/java/com/cooper/wheellog/BluetoothLeService.java
  app/src/main/java/com/cooper/wheellog/MainActivity.java
  app/src/main/java/com/cooper/wheellog/ViewPageAdapter.java
  app/src/main/java/com/cooper/wheellog/WheelData.java
Labels: enhancement

#27 Fix NRE in PebbleService
  app/src/main/java/com/cooper/wheellog/PebbleService.java
Labels: bug

#28 fix NRE in LoggingService
  app/src/main/java/com/cooper/wheellog/LoggingService.java
Labels: bug

#32 dynamic key-value views on second page
  app/src/main/java/com/cooper/wheellog/MainActivity.java
  app/src/main/res/layout/main_view_two.xml
  app/src/main/res/layout/textview_title_template.xml
  app/src/main/res/layout/textview_value_template.xml
Labels: breaking change, enhancement

#40 fix arcs on the main screen for non-standard screens
  app/src/main/java/com/cooper/wheellog/views/WheelView.java
Labels: bug
